
package com.atguigu.ws.service;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "BookService", targetNamespace = "http://service.ws.atguigu.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface BookService {


    /**
     * 
     * @return
     *     returns java.util.List<com.atguigu.ws.service.Book>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getAll", targetNamespace = "http://service.ws.atguigu.com/", className = "com.atguigu.ws.service.GetAll")
    @ResponseWrapper(localName = "getAllResponse", targetNamespace = "http://service.ws.atguigu.com/", className = "com.atguigu.ws.service.GetAllResponse")
    public List<Book> getAll();

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "save", targetNamespace = "http://service.ws.atguigu.com/", className = "com.atguigu.ws.service.Save")
    @ResponseWrapper(localName = "saveResponse", targetNamespace = "http://service.ws.atguigu.com/", className = "com.atguigu.ws.service.SaveResponse")
    public boolean save(
        @WebParam(name = "arg0", targetNamespace = "")
        Book arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "update", targetNamespace = "http://service.ws.atguigu.com/", className = "com.atguigu.ws.service.Update")
    @ResponseWrapper(localName = "updateResponse", targetNamespace = "http://service.ws.atguigu.com/", className = "com.atguigu.ws.service.UpdateResponse")
    public boolean update(
        @WebParam(name = "arg0", targetNamespace = "")
        Book arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns boolean
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "delete", targetNamespace = "http://service.ws.atguigu.com/", className = "com.atguigu.ws.service.Delete")
    @ResponseWrapper(localName = "deleteResponse", targetNamespace = "http://service.ws.atguigu.com/", className = "com.atguigu.ws.service.DeleteResponse")
    public boolean delete(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.atguigu.ws.service.Book
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getById", targetNamespace = "http://service.ws.atguigu.com/", className = "com.atguigu.ws.service.GetById")
    @ResponseWrapper(localName = "getByIdResponse", targetNamespace = "http://service.ws.atguigu.com/", className = "com.atguigu.ws.service.GetByIdResponse")
    public Book getById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @return
     *     returns com.atguigu.ws.service.GetMapResponse.Return
     */
    @WebMethod
    @WebResult(name = "_return", targetNamespace = "")
    @RequestWrapper(localName = "getMap", targetNamespace = "http://service.ws.atguigu.com/", className = "com.atguigu.ws.service.GetMap")
    @ResponseWrapper(localName = "getMapResponse", targetNamespace = "http://service.ws.atguigu.com/", className = "com.atguigu.ws.service.GetMapResponse")
    public com.atguigu.ws.service.GetMapResponse.Return getMap();

}
